source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/envs.conf
source = ~/.config/hypr/config/permissions.conf
source = ~/.config/hypr/config/looks.conf
source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/inputs.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/window-rules.conf
