input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = caps:escape,ctrl:swap_lalt_lctl,altwin:swap_ralt_rwin
    kb_rules =

    repeat_delay = 500
    repeat_rate = 25

    follow_mouse = 1

    sensitivity = 0

    touchpad {
        natural_scroll = true
        scroll_factor = 0.25
    }
}

# gesture = 4, horizontal, workspace

cursor {
    inactive_timeout = 1
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

xwayland {
    force_zero_scaling = true
}
